### ISSUE TITLE
Arbitrary flux pattern method for MoveableGrid

### ISSUE THREAD

**Issue by mbaumer** [cpadavis/weak_sauce#1]
We have uniform_flux() to make simulated flats; need a new source function that can be called in MoveableGrid.update_fluxes()

**Comment by cpadavis** [comment]
we now have code that can integrate arbitrary things:

![screenshot 2015-04-22 12 47 45](https://cloud.githubusercontent.com/assets/1781988/7284079/ed2d0f58-e8ef-11e4-816b-2597756fe4fc.png)

next is to make it something that can be called in update_fluxes

**Comment by mbaumer** [comment]
Awesome! Sorry I couldn't get to this earlier. One thing I noticed messing around with the source function is that sometimes a few pixels would end up blank (see below). Different pixels fail as you re-run the same code, so I assume it's a convergence/numerical issue?

![image](https://cloud.githubusercontent.com/assets/7607631/7294208/d85fc58c-e95f-11e4-9a7e-d0182b8fefb7.png)

![image](https://cloud.githubusercontent.com/assets/7607631/7294213/e01c8800-e95f-11e4-9949-f1db07402809.png)

![image](https://cloud.githubusercontent.com/assets/7607631/7294215/e5bd7f6c-e95f-11e4-9fb0-f488779e174f.png)

**Comment by cpadavis** [comment]
any ideas @devonmpowell ?

**Comment by devonmpowell** [comment]
Probably an issue with passing NumPy arrays to r2d as C pointers... I'm not really sure how this could happen, but maybe r2d is depositing flux somewhere else in memory?
Proposed test: Add a printf() in the C code to declare how much flux was deposited vs. is seen by Python.

**Comment by cpadavis** [comment]
fixed! turns out to have to do with the memory allocated with r2d_init. Just needed to make that a bit bigger and the problem went away
