### ISSUE TITLE
Fitting fails on non-square cutouts

### ISSUE THREAD

**Issue by mbaumer** [cpadavis/weak_sauce#18]
Hey @cpadavis, not sure if you've seen this before or if I'm doing something wrong, but whenever I try to run our fitter on non-square images, the fitted fluxes are offset from ~1 by an amount that depends on how non-square it is.

**Comment by mbaumer** [comment]
See the demo nb in above commit...any ideas?

**Comment by cpadavis** [comment]
turned out the issue was that by default we created square coordinate systems instead of square pixels. That is now fixed
