### ISSUE TITLE
Apply to DES flats using LSST methods

### ISSUE THREAD

**Issue by mbaumer** [cpadavis/weak_sauce#6]

**Comment by mbaumer** [comment]
TODO: use easyAccess to download, coadd, and then delete as many flats as possible

**Comment by cpadavis** [comment]
currently bulk downloading dome flats on ki-ls. (might run out of disk space :p) Regardless, code for acquiring the flats is now in the repository under download_flats.py -- it now just needs some kind of do_coadd function!

**Comment by cpadavis** [comment]
oh and location is /nfs/slac/g/ki/ki18/des/cpd/flats

**Comment by cpadavis** [comment]
oh since I didn't report it here, Mike and I decided that instead of downloading 30k flats, we could just use the 248 g-band flats I had already downloaded (~153 gb total)

so now we need to coadd them

**Comment by mbaumer** [comment]
per this morning's discussion, lots of supercal flatcors inbound to /nfs/slac/g/ki/ki19/lsst/mbaumer/DES_flatcor_supercal

**Comment by cpadavis** [comment]
per this afternoon's discussion, let's move these DES supercals into a DES
area

**Comment by mbaumer** [comment]
Downloaded flats are in /nfs/slac/g/ki/ki19/des/mbaumer/DES_flatcor_supercal/
Coadds are in coadds/ subfolder

**Comment by mbaumer** [comment]
done
